CREATE TABLE IF NOT EXISTS users(
	id BIGSERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	mobile VARCHAR(255) NOT NULL,
	longitude DOUBLE PRECISION,
	latitude  DOUBLE PRECISION,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS products(
	id BIGSERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	images VARCHAR [] NOT NULL,
	price BIGINT NOT NULL,
	compressed_images VARCHAR [],
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO users (name, mobile, longitude, latitude, created_at, updated_at) VALUES
("venkat", "6380617798", 90.2, 180.36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);